import type { DailyMessageCategory } from "./validation";

type SeedSource = { sourceName: string; sourceUrl: string };

export type DailyMessageSeed = SeedSource & {
  text: string;
  category: DailyMessageCategory;
  status: "pending";
};

const SOURCES = {
  ooe: {
    sourceName: "Oberösterreich Tourismus: Oberösterreichs Mundart",
    sourceUrl:
      "https://medienservice.oberoesterreich.at/oberoesterreich-woerterbuch.html",
  },
  oewb: {
    sourceName: "Österreichisches Wörterbuch: Österreich von A bis Z",
    sourceUrl: "https://www.oebv.at/oewb-70-jahre",
  },
  oeaw: {
    sourceName: "ÖAW: Wörterbuch der bairischen Mundarten in Österreich",
    sourceUrl:
      "https://www.oeaw.ac.at/de/acdh/forschung/sprachwissenschaft/ressourcen/woerterbuecher/wboe-online-woerterbuch",
  },
  sprachportal: {
    sourceName: "ÖIF Sprachportal: Österreichisches Deutsch",
    sourceUrl:
      "https://sprachportal.at/fileadmin/user_upload/meinsprachportal-at/OEsterreich_Spiegel/Ausgabe_98/Schwerpunkt_Spiegel_98.pdf",
  },
} satisfies Record<string, SeedSource>;

function seeds(
  category: DailyMessageCategory,
  source: SeedSource,
  texts: string[],
): DailyMessageSeed[] {
  return texts.map((text) => ({ ...source, text, category, status: "pending" }));
}

const DIALECT = seeds("dialect", SOURCES.oewb, [
  "Jause: die österreichische Pause mit etwas Gutem zum Essen",
  "Sackerl: eine Tasche die in Österreich ganz selbstverständlich so heißt",
  "Paradeiser: die ostösterreichische Antwort auf die Tomate",
  "Erdäpfel: Kartoffeln mit österreichischem Boden unter den Füßen",
  "Marille: die österreichische Verwandte der Aprikose",
  "Fisolen: grüne Bohnen auf gut österreichisch",
  "Karfiol: der Blumenkohl mit österreichischem Namen",
  "Kren: scharfer Meerrettich der in Österreich lieber kurz heißt",
  "Topfen: österreichischer Quark für Strudel und andere gute Ideen",
  "Obers: Schlagrahm bevor er geschlagen wird",
  "Palatschinke: dünner Genuss der selten lange am Teller bleibt",
  "Ribisel: kleine Beeren mit großem österreichischem Namen",
  "Zwetschke: die Frucht die besonders gern im Knödel landet",
  "Vogerlsalat: Feldsalat mit einem Namen zum Zwitschern",
  "Melanzani: Aubergine auf österreichischen Speisekarten",
  "Kukuruz: Mais der schon beim Aussprechen gute Laune macht",
  "Powidl: dunkles Zwetschkenmus mit böhmisch österreichischer Geschichte",
  "Germ: Hefe die einem Teig beim Wachsen hilft",
  "Semmel: das runde Frühstücksgebäck mit Wiener Wurzeln",
  "Weckerl: kleines Gebäck für großen Jausenhunger",
  "Staubzucker: Puderzucker der sich in Österreich fein macht",
  "Faschiertes: Hackfleisch mit österreichischem Reisepass",
  "Stelze: Schweinshaxe wie sie in Österreich auf der Karte steht",
  "Grammeln: knusprige kleine Stücke mit großem Geschmack",
  "Most: vergorener Apfel oder Birnensaft mit Landpartiegefühl",
  "Sturm: junger Wein der im Glas mehr braust als am Himmel",
  "Gespritzter: Wein und Soda als österreichisches Doppel",
  "Verlängerter: Kaffee der mit heißem Wasser länger wird",
  "Melange: Wiener Kaffee mit Milch und Milchschaum",
  "Einspänner: Wiener Kaffee im Glas mit einer Haube aus Obers",
  "Häferl: ein Becher der gern Kaffee oder Kakao beherbergt",
  "Bim: die Straßenbahn mit dem kürzesten Namen in Wien",
  "Mistkübel: der österreichische Platz für alles was weg kann",
  "Stiege: eine Treppe die in Österreich aufwärts führt",
  "Kasten: in Österreich oft ein Schrank und nicht nur eine Kiste",
  "Polster: ein Kissen auf dem man besonders österreichisch ruht",
  "Tuchent: die Bettdecke die einen in Österreich warm hält",
  "Gewand: Kleidung vom feinen Zwirn bis zur alten Jogginghose",
  "Patschen: Hausschuhe oder das Ergebnis eines platten Reifens",
  "Pickerl: ein Aufkleber oder die Prüfplakette fürs Auto",
  "Spital: das Krankenhaus mit österreichischem Klang",
  "Ordination: die Praxis einer Ärztin oder eines Arztes",
  "Trafik: kleines Geschäft für Zeitungen und vieles mehr",
  "Jänner: der erste Monat des Jahres in Österreich",
  "Heuer: dieses Jahr in einem einzigen österreichischen Wort",
  "Leiwand: erfreulich großartig oder einfach richtig gut",
  "Zach: mühsam anstrengend oder überraschend hartnäckig",
  "Fad: langweilig oder geschmacklich nicht besonders aufregend",
  "Narrisch: verrückt begeistert oder ordentlich aufgebracht",
  "Patschert: ungeschickt aber meistens liebenswert",
  "Grantig: schlecht gelaunt mit besonderem Wiener Nachdruck",
  "Gschamig: schüchtern oder ein bisserl verlegen",
  "Goschert: frech und nicht gerade auf den Mund gefallen",
  "Liab: nett herzlich oder einfach zum Gernhaben",
  "Wurscht: egal mit einem Hauch österreichischer Gelassenheit",
  "Eh: ein kleines Wort das in Österreich erstaunlich viel kann",
  "Ur: macht etwas in Wien besonders groß schnell oder leiwand",
  "Bisserl: eine kleine Menge mit viel Gemütlichkeit",
  "Gach: plötzlich schnell oder vielleicht doch ein wenig voreilig",
  "Hudeln: sich so beeilen dass am Ende alles länger dauert",
]);

const DIALECT_MORE = seeds("dialect", SOURCES.oeaw, [
  "Raunzen: hörbar unzufrieden sein ohne gleich aufzugeben",
  "Tratschen: Neuigkeiten in gemütlicher Gesellschaft austauschen",
  "Hackeln: arbeiten auf österreichisch und oft mit Nachdruck",
  "Jausnen: eine Pause in eine kleine Mahlzeit verwandeln",
  "Buckelkraxen: jemanden auf dem Rücken tragen",
  "Busserl: ein kleiner Kuss mit österreichischem Charme",
  "Gspusi: eine Liebschaft die noch nicht alles verrät",
  "Strizzi: ein Gauner oder charmanter Hallodri je nach Tonfall",
  "Zniachterl: jemand oder etwas klein Geratenes",
  "Wimmerl: ein kleiner Pickel mit großem Nervfaktor",
  "Nackerpatzerl: ein liebevolles Wort für einen kleinen Nackedei",
  "Gfrast: freches Kind oder lästiger Mensch je nach Zuneigung",
  "Oida: Anrede Staunen Ärger und Freude in einem Wort",
  "Pfiat di: ein Abschiedsgruß mit guten Wünschen im Gepäck",
  "Servus: Begrüßung und Abschied bequem in einem Wort",
  "Baba: ein kurzer österreichischer Abschied ohne langes Tamtam",
  "Griaß di: eine herzliche Begrüßung in vielen österreichischen Regionen",
  "Drawig: eilig wenn es in Oberösterreich schnell gehen muss",
  "A Neichtl: eine kleine Weile in oberösterreichischer Mundart",
  "Beng: eine Bank auf der man in Oberösterreich Platz nimmt",
]);

const JOKES = seeds("joke", SOURCES.ooe, [
  "Warum fährt die Schnecke mit der Bim? Zu Fuß ist ihr Wien zu schnell",
  "Was sagt die Semmel zum Kren? Du bist aber scharf drauf",
  "Warum ging der Kalender auf die Alm? Er brauchte mehr freie Tage",
  "Was macht ein Berg im Kaffeehaus? Er bestellt einen Gipfel",
  "Warum steht der Paradeiser im Stau? Er kommt nicht aus dem Ketchup",
  "Was sagt das Schnitzel zur Panier? Schön dass du mich einpackst",
  "Warum nimmt die Kuh die Seilbahn? Sie will hoch hinaus",
  "Was trinkt der Computer im Kaffeehaus? Einen Java mit Obers",
  "Warum ist die Bim selten beleidigt? Sie fährt einfach drüber",
  "Was macht die Wolke über Wien? Sie schaut auf einen Sprung vorbei",
  "Warum trägt der Knödel einen Mantel? Weil es im Topf zieht",
  "Was sagt der Krapfen nach der Jause? Jetzt bin ich ausgezuckert",
  "Warum hat der Apfel einen Regenschirm? Er rechnet mit Most",
  "Wie grüßt ein höflicher Erdäpfel? Habe die Knödel",
  "Warum kann die Melange gut trösten? Sie hat viel Schaumgefühl",
  "Was sagt der Lift am Großglockner? Heute geht es aufwärts",
  "Warum ist die Marille so ruhig? Sie bewahrt den Kern der Sache",
  "Was macht ein Pinguin am Neusiedler See? Urlaub vom Eis",
  "Warum war die Ziehharmonika müde? Sie hatte einen langen Zug",
  "Was sagt die Donau beim Abschied? Ich bin dann mal im Fluss",
  "Warum ging das Kipferl früh schlafen? Es war schon ganz mürbe",
  "Was macht der Kater im Kaffeehaus? Er bestellt einen Mokka miau",
  "Warum lacht der Kürbis in der Steiermark? Er findet alles kernig",
  "Was sagt der Schnee zur Schaufel? Heb dir das für später auf",
  "Warum kam die Palatschinke zu spät? Sie hat sich vertrödelt und gewendet",
  "Was macht die Ampel beim Heurigen? Sie gibt dem Grünen den Vortritt",
  "Warum kann der Gugelhupf gut zuhören? Er hat ein Loch für jedes Geheimnis",
  "Was sagt der Polster am Morgen? Bleib ruhig noch ein bisserl",
  "Warum mag der Föhn die Alpen? Dort kann er richtig durchziehen",
  "Was bestellt die Uhr beim Würstelstand? Eine Käsekrainer rund um die Uhr",
  "Warum nimmt der Kaffee die Stiege? Der Lift ist ihm zu aufgschäumt",
  "Was sagt die Brezel zur Semmel? Du bist heute aber rund drauf",
  "Warum hat der See keinen Stress? Er lässt die Dinge treiben",
  "Was macht ein Grantler im Chor? Er singt nur die Misstöne",
  "Warum kennt der Berg keinen Montag? Er hat jeden Tag einen Gipfel",
  "Was sagt der Regenschirm in Salzburg? Ohne mich wird das nix",
  "Warum spielt der Knödel Verstecken? Im Gulasch findet ihn keiner",
  "Was macht die Kuh in der Trafik? Sie holt die Muhgenpost",
  "Warum ist die Jause pünktlich? Sie kommt genau zwischen Hunger und Abendessen",
  "Was sagt der Marillenknödel zur Waage? Heute bitte nicht stören",
  "Warum braucht der Fiaker kein Navi? Die Pferde kennen den Schmäh",
  "Was macht die Semmel auf der Alm? Sie wird zum Gipfelstürmer",
  "Warum war der Kren beim Arzt? Ihm war alles zu fad",
  "Was sagt der Donauturm zum Stephansdom? Schöne Aussicht Kollege",
  "Warum telefoniert der Käsekrainer nicht? Sie hat schon genug Empfang",
  "Was macht ein Erdäpfel im Fitnessstudio? Knödeltraining",
  "Warum hat die Bim eine Glocke? Damit Wien weiß dass sie unterwegs ist",
  "Was sagt der Kaffee zur Müdigkeit? Mit mir hast du ausgesudert",
  "Warum ging der Apfel zum Heurigen? Er wollte seinen Mostrich treffen",
  "Was macht ein Schaf im Prater? Eine Wollfahrt",
  "Warum ist der Gugelhupf so beliebt? Er lässt niemanden am Rand stehen",
  "Was sagt die Alm zur Stadt? Bei mir ist die Aussicht besser",
  "Warum hat der Punsch einen Schal? Weil ihm winterlich zumute ist",
  "Was macht die Melanzani im Theater? Sie spielt die Aubergine ihres Lebens",
  "Warum war der Sturm so gesprächig? Er war noch sehr jung",
  "Was sagt der Mistkübel nach dem Putzen? Das war für die Tonne",
  "Warum ist der Walzer nie allein? Er kommt immer im Dreivierteltakt",
  "Was macht der Mond über Ottenschlag? Er hält die Nachtschicht",
  "Warum ging die Kuh ins Kaffeehaus? Wegen der Melange mit Muh",
  "Was sagt der Winter zur Wachau? Heb mir ein paar Marillen auf",
]);

const BONMOTS = seeds("bonmot", SOURCES.sprachportal, [
  "A bisserl Gemütlichkeit geht immer",
  "Wer langsam genießt hat länger was von der Jause",
  "In Österreich ist eh oft eine vollständige Antwort",
  "Der frühe Vogel kann mich nach dem Kaffee noch einmal fragen",
  "Ein guter Schmäh braucht keine Bedienungsanleitung",
  "Zwischen jetzt und gleich passt noch ein Kaffee",
  "A guate Jause ist die kürzeste Form von Urlaub",
  "Wer raunzt hat noch Hoffnung dass es wer hört",
  "Gelassenheit heißt wissen wann man net hudeln soll",
  "Manche Gipfel erreicht man am besten mit der Seilbahn",
  "Kaffee löst keine Probleme aber er macht sie höflicher",
  "Wo ein Wille ist ist meistens auch ein Umweg",
  "A bisserl später ist inoffiziell auch eine Uhrzeit",
  "Der Schmäh rennt am besten ohne Stoppuhr",
  "Ein leerer Teller ist das schönste Kompliment an die Köchin",
  "Heut wird ein guter Tag und wenn net dann wenigstens eine gute Jause",
  "Gemütlichkeit ist Geschwindigkeit ohne schlechtes Gewissen",
  "Wer den Knödel ehrt ist das Gulasch wert",
  "Der kürzeste Weg zum Wochenende führt durch den Freitag",
  "Ein Busserl ist klein und trotzdem selten unbemerkt",
  "Morgenstund hat Kaffee im Mund",
  "Wenn schon warten dann wenigstens bequem",
  "Das Leben ist zu kurz für faden Kuchen",
  "A bissl Schmäh macht aus einem Weg einen Spaziergang",
  "Wer zuletzt lacht hat den Witz endlich verstanden",
  "Pünktlichkeit ist wenn beide ungefähr gleichzeitig zu spät kommen",
  "Ein voller Kühlschrank ist noch kein Plan aber ein guter Anfang",
  "Man muss nicht alles wissen man kann auch freundlich nachfragen",
  "Der beste Platz im Haus ist dort wo die Jause steht",
  "A ruhiger Tag ist auch eine kleine Sensation",
  "Wer den Kaffee teilt hat mehr vom Plaudern",
  "Gute Laune ist kein Wetterbericht",
  "Der Umweg über das Kaffeehaus ist manchmal der direkte Weg",
  "Ein Lächeln passt in jedes Sackerl",
  "Wer Pause macht gibt dem Tag eine zweite Chance",
  "Manche Gedanken brauchen erst ein Häferl Ruhe",
  "Ein Plan ohne Jause ist nur ein Entwurf",
  "Wo gehobelt wird ist eine Werkstatt nicht weit",
  "A gute Idee erkennt man daran dass noch Platz für Kuchen bleibt",
  "Der Tag ist jung der Kaffee ist stärker",
  "Man kann nicht alles haben aber man kann nachbestellen",
  "Wer freundlich grüßt bekommt oft ein Lächeln retour",
  "Auch ein kleiner Schritt kann leiwand sein",
  "Zwischen Grant und Glück liegt manchmal nur eine Semmel",
  "Die Aussicht wird besser wenn man den Blick hebt",
  "Daheim ist wo man die Patschen findet",
  "Ein gutes Gespräch misst man nicht in Minuten",
  "Wer sich Zeit nimmt hat plötzlich mehr davon",
  "Die besten Geschichten beginnen selten mit einem Zeitplan",
  "Ein Regentag ist Sonnenschein mit Anlauf",
  "A bisserl Neugier hält den Kopf in Bewegung",
  "Wer den Schmäh versteht ist schon halb daheim",
  "Ein leerer Terminkalender kann voller Möglichkeiten sein",
  "Die Ruhe vor dem Kaffee ist meistens nur Müdigkeit",
  "Manches geht sich aus weil man es einfach probiert",
  "Wer Umwege kennt kann mehr Geschichten erzählen",
  "Der Sonntag ist die Jause unter den Wochentagen",
  "Ein warmer Strudel ist ein ziemlich guter Tagesplan",
  "A freundliches Servus öffnet erstaunlich viele Türen",
  "Die beste Abkürzung ist manchmal eine gemütliche Pause",
]);

const SAYINGS = seeds("saying", SOURCES.sprachportal, [
  "Nur net hudeln dann bleibt Zeit fürs Wesentliche",
  "Viele kleine Freuden machen einen großen Tag",
  "Wer gut zuhört hört mehr als Worte",
  "Gemeinsam schmeckt auch die einfache Jause besser",
  "Nach jedem Regen riecht die Welt ein bisserl neuer",
  "Ein freundliches Wort braucht wenig Platz",
  "Heute anfangen ist besser als morgen perfekt sein",
  "Auch der längste Weg beginnt vor der Haustür",
  "Wer teilt hat doppelt Grund zur Freude",
  "Ein ruhiger Kopf findet auch im Nebel den Weg",
  "Kleine Pausen tragen weit",
  "Wo gelacht wird fühlt sich ein Zuhause wohl",
  "Gute Nachbarn sind näher als ferne Sorgen",
  "Wer den Tag begrüßt bekommt oft ein Servus zurück",
  "Ein Schritt nach dem anderen führt auch auf den Gipfel",
  "Man muss den Tag nicht hetzen er kommt von selber",
  "Freude wächst wenn man sie weitererzählt",
  "Ein gedeckter Tisch bringt Menschen zusammen",
  "Die besten Erinnerungen brauchen selten viel Gepäck",
  "Wer neugierig bleibt entdeckt auch bekannte Wege neu",
  "Ein gutes Wort wärmt länger als eine kurze Sonne",
  "Auch graue Wolken kennen eine helle Rückseite",
  "Zeit für Menschen ist niemals verlorene Zeit",
  "Wer Fehler macht ist wenigstens unterwegs",
  "Ein kleiner Gruß kann einen großen Unterschied machen",
  "Gelassenheit beginnt mit einem tiefen Atemzug",
  "Miteinander wird aus wenig oft genug",
  "Jeder Tag hat irgendwo eine gute Aussicht",
  "Wer anderen Mut macht wird selber mutiger",
  "Ein offenes Ohr ist ein stilles Geschenk",
  "Manchmal ist langsam genau das richtige Tempo",
  "Ein ehrliches Danke passt zu jeder Gelegenheit",
  "Wo Vertrauen wächst wird der Weg leichter",
  "Ein gemütlicher Umweg kann das schönste Stück Weg sein",
  "Die kleinen Dinge sind oft die großen Erinnerungen",
  "Ein neuer Morgen kennt die Fehler von gestern nicht",
  "Wer miteinander redet muss weniger übereinander rätseln",
  "Ein gutes Essen beginnt mit Vorfreude",
  "Man sieht weiter wenn man nicht nur auf die Füße schaut",
  "Ein bisschen Humor macht schwere Taschen leichter",
  "Wer willkommen sagt macht aus einem Ort ein Zuhause",
  "Jeder Mensch kennt einen Weg den sonst niemand kennt",
  "Ein stiller Moment kann ziemlich viel erzählen",
  "Was heute klein wirkt kann morgen wichtig sein",
  "Gute Ideen mögen frische Luft und warme Getränke",
  "Wer sich selber Zeit gibt kommt entspannter an",
  "Ein gemeinsamer Kaffee ist oft der Anfang einer Lösung",
  "Auch ein Regentropfen gehört zum Wetterglück",
  "Wer fragt findet Türen die vorher unsichtbar waren",
  "Ein freundlicher Blick reist ohne Fahrkarte",
  "Die beste Zeit für ein gutes Wort ist meistens jetzt",
  "Aus einem kleinen Plan kann ein schöner Tag werden",
  "Wer über sich lachen kann hat immer gute Gesellschaft",
  "Ein warmer Platz ist noch schöner wenn man ihn teilt",
  "Zuversicht ist ein Regenschirm für Gedanken",
  "Wer jeden Tag etwas entdeckt bleibt innerlich unterwegs",
  "Ein gutes Ende darf gemütlich beginnen",
  "Manchmal reicht ein Servus damit niemand allein bleibt",
  "Aus Ruhe wächst oft die klarste Antwort",
  "Ein schöner Tag muss nicht laut sein",
]);

export const DAILY_MESSAGE_SEEDS = [
  ...DIALECT,
  ...DIALECT_MORE,
  ...JOKES,
  ...BONMOTS,
  ...SAYINGS,
];

