[platformio]
default_envs = lolin32

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_speed = 115200
build_flags =
    -D FAMILY_TOUCH_SWAP_XY=0
    -D FAMILY_TOUCH_MIRROR_X=0
    -D FAMILY_TOUCH_MIRROR_Y=0
    -D FAMILY_EPD_INVERT_TRANSFER_BITS=0

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<bitmap_canvas.cpp> +<family_types.cpp> +<touch_tracker.cpp>
